db:
  image: postgres
redis:
  image: redis
web:
  build: .
  command: ./run.sh
  volumes:
    - .:/code
    - ../django-report-utils/report_utils:/usr/local/lib/python3.4/site-packages/report_utils
    #- ../django-custom-field/custom_field:/usr/local/lib/python3.4/site-packages/custom_field
  ports:
    - "8000:8000"
  links:
    - db
    - redis
